language: osx
osx_image: xcode10.2

script:
    - xcodebuild clean test -project SwiftTrigger.xcodeproj -scheme Trigger -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

