# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TriggerExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TriggerExample
  pod 'SwiftTrigger', '~> 0.1.8'

  target 'TriggerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
